### ISSUE TITLE
Error::status is private, preventing me from handling particular error type

### ISSUE THREAD

**Issue by Fiedzia** [zonyitoo/memcached-rs#6]
I'd like to detect and handle KeyNotFound error when deleting a key from memcached.
I can get memcached::proto::binary::Error, but I cannot distinguish particular error because status type is private and there is no other way to get it. Could it be made public?

**Comment by zonyitoo** [comment]
Is that Ok for you?

**Comment by Fiedzia** [comment]
That will do, thanks

**Comment by zonyitoo** [comment]
Published `v0.1.4`
